### ISSUE TITLE
How to calculate the value of pathway?

### ISSUE THREAD

**Issue by xuechunxu** [bjtully/BioData#1]
Hi,

The KEGG-decoder.py is very helpful to census pathways of the genome.
While I am a little confused about `How to calculate the value of pathway`.
For example:
`#norBC  
	if ('K04561' in ko_match and 'K02305' in ko_match):  
		out_data['nitric oxide reduction'] = 1`  
`#nifKDH`  
`#	if ('K02586' in ko_match and 'K02591' in ko_match and 'K02588' in ko_match):`  
`#		out_data['nitrogen fixation'] = 1`  
	`if ('K02586' in ko_match):  
		out_data['nitrogen fixation'] += 0.33  
	if ('K02591' in ko_match):  
		out_data['nitrogen fixation'] += 0.33  
	if ('K02588' in ko_match):  
		out_data['nitrogen fixation'] += 0.33`  

For nitric oxide reduction, the value of nitric oxide reduction is one when both K04561 and K02305 must be present.
While for nitrogen fixation, the value of nitrogen fixation is the added value of each KO.

Best
chunxu

**Comment by bjtully** [comment]
Hi Chunxu,

This a personal preference of mine - I was unhappy with searches for norB without norD as I felt it was overestimating the number of organism with a putatively functional nitric oxide reductase. In early versions of the tool, nitrogen fixation was treated the same way, but I was convinced to provide a partial calculation.

Cheers
Ben

**Comment by bjtully** [comment]
Intentional distinction between the observation of these functions
