### ISSUE TITLE
update pypi install to accomodate tanglegram

### ISSUE THREAD

**Issue by taylorreiter** [bjtully/BioData#17]
- [x] deal with the dependency issue for the [tanglegram code](https://github.com/schlegelp/tanglegram/issues/4)
- [ ] if tanglegram becomes available on pypi, update license to GPL.
- [x] update toml file for new dependencies, including tanglegram function imports:
```
import itertools
from Bio import Phylo
import tanglegram as tg
from scipy.spatial.distance import pdist, squareform
```

**Comment by taylorreiter** [comment]
tanglegram package is now pip installable!

**Comment by bjtully** [comment]
That's exciting!

Let me ask a question - does it make the most sense to wrap the tanglegram code within KEGGDecoder, when an option could be to have KEGGDecoder generate the distance file needed for input into tanglegram? That way if tanglegram is updated in the future it wouldn't break out code (say they add a new functionality or required input...). Thoughts? @luizirber @taylorreiter

**Comment by taylorreiter** [comment]
I think that's a great idea! I'll add the tanglegram to the binder repo so others can see how to make it.

**Comment by bjtully** [comment]
I'm closing this issue due to the expanded use and integration of tanglegram!
