### ISSUE TITLE
"Bio" module not installing properly

### ISSUE THREAD

**Issue by bjtully** [bjtully/BioData#21]
@taylorreiter ran into an issue while pushing updates yesterday, addition of Bio or biopython as modules through toml does not create a version of KEGG-decoder 'tanglegram' that produces an output. Any insight as to the correct module to install?

Other elements still run correctly.

**Comment by taylorreiter** [comment]
umm this is odd. was this a travis failure or something that failed locally?

**Comment by bjtully** [comment]
@taylorreiter It happens at the pip install step. I tried the two different names of the Bio module that I could find. The pip install seems to work correctly and then running the tanglegram option throws an error about not finding the module.

**Comment by taylorreiter** [comment]
oh! ok, did you try `pip install biopython`?

**Comment by bjtully** [comment]
I have not. Though that would be troubling that the project toml couldn't install biopython properly...

**Comment by taylorreiter** [comment]
yes I agree. `import Bio` is for `biopython` though. Am I asking the right questions or do I not understand the problem?

**Comment by bjtully** [comment]
No, you are understanding correctly.

**Comment by jzrapp** [comment]
Hi,

I'm using the decoder for the first time (and love it!).

I installed it:`python3 -m pip install KEGGDecoder`

And `KEGG-decoder --input KEGG_DECODER_in_all.txt --output FUNCTION_OUT_ALL.list --vizoption static` runs perfectly fine. 
However, when I try to pair it with a newick:
`KEGG-decoder --input KEGG_DECODER_in_all_match_tree.txt --output FUNCTION_OUT_ALL.list --vizoption tanglegram --newick tree_output` it produces this error: 

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/KEGG-decoder", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/KEGGDecoder/KEGG_decoder.py", line 1390, in main
    make_tanglegram(genome, str(arg_dict['newick']))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/KEGGDecoder/MakeTanglegram.py", line 20, in make_tanglegram
    genome_df = pd.read_csv(genome_df, index_col=0, sep='\t')
NameError: name 'pd' is not defined
```

Any idea what's wrong? Thanks a lot!

**Comment by bjtully** [comment]
Thanks for the issue @jzrapp the tanglegram option has been causing some headaches. We are working on a fix.

**Comment by taylorreiter** [comment]
@jzrapp this is particularly weird...the main function imports pandas: `import pandas as pd`, but then says its not defined. As @bjtully noted, we are working on fixing this!

**Comment by taylorreiter** [comment]
@bjtully i wonder if #22 will solve this problem? the tanglegram function was not importing pandas, and it requires pandas. Without that library it should not produce an output

**Comment by bjtully** [comment]
Now fixed.
