### ISSUE TITLE
Can Kegg decoder be adapted to predict the completeness of Kegg modules? 

### ISSUE THREAD

**Issue by SilasK** [bjtully/BioData#23]

**Comment by bjtully** [comment]
What did you have in mind? All modules? Specific modules? Many of the pathways function in a similar way to the KEGG modules. Some are modified modules.

**Comment by SilasK** [comment]
Yes use all modules instead or in addition to pathways.
I would say that kegg pathways are too global.

**Comment by bjtully** [comment]
Thanks for the input. These are not KEGG pathways. The biogeochemically-relevant pathways are manually assessed and limited to the specific components in one pathway.
