### ISSUE TITLE
ubiquinol-cytochrome c reductase

### ISSUE THREAD

**Issue by gchadwick** [bjtully/BioData#35]
Hi,
Thanks a lot for the nice tool, apologies if this is not where to ask this sort of question.  For ubiquinol-cytochrome c reductase you are using K00411 (PetA) and K00410 (FbcH).  K00410 is a fusion of K00412 (PetB) and K00413 (PetC).  Almost nothing has FbcH except a few proteobacteria as far as I can tell, so ubiquinol-cytochrome c reductase is almost always incomplete in your tables.  Following the kegg presence logic in this module might be best as a general representation for complex III-like things? https://www.genome.jp/dbget-bin/www_bget?M00151 with the definition ((K00412+K00413,K00410)+K00411),K03886+K03887+K03888,K03890+K03891+K03889, but at the very least probably best to do PetABC (K00411,12,13) with 0.33 presence value each instead of 0.5 value for PetA and FbcH.
Also not sure what the significance is of 859-860 in KEGG_decoder.py since its in the ubiquinol-cytochrome c reductase section but is doing stuff with 'NADH-quinone oxidoreductase'
Best,
Gray

**Comment by bjtully** [comment]
Thanks for catching this, Grayson. I've made suitable changes to address this. KEGG-Decoder now first looks to see if both PetA and FbcH are present (must both be present). If not, KEGG-Decoder now systematically checks for PetA, PetB, PetC, each valued are 0.33. 

'NADH-quinone oxidoreductase' lines were moved to the correct spot it was referencing.
