### ISSUE TITLE
what cut-off to use for "almost complete" pathways?

### ISSUE THREAD

**Issue by Jigyasa3** [bjtully/BioData#38]
Hey!

I want to ask that based on the heatmap output, what is the best cut-off to use for "almost complete pathway" analysis in metagenomes?
If I have pathways with completeness greater than 0.6, would that be a good estimate of "almost complete" pathways?
Would you recommend only using "complete" pathways i.e. completeness =1 for downstream analysis?

**Comment by bjtully** [comment]
This is very much dependent on the pathway in question (and how complete the genome being queried is). There are a number of pathways, such as the TCA cycle, where a low completeness score (~0.4) could be acceptable. Other pathways, such as 3-hydroxypropionate 4-hydroxybutyrate cycle, which has components that are common in other metabolisms, would benefit from a more strict cut-off (>=0.5).
