### ISSUE TITLE
pip installation not working with python 3.8

### ISSUE THREAD

**Issue by hdore** [bjtully/BioData#44]
Hi,

I tried to install KEGGdecoder with pip and it would not work with python 3.8. Switching to python 3.7 solved the problem.
I think the error came from the installation of numpy (from what I understand of the long error log from pip).

I just thought this might be useful for others.

Hugo

**Comment by bjtully** [comment]
Thanks, Hugo.

I'll have to see if I can track this issue down. Seems to be something with how matplotlib interacts with python 3.8

**Comment by spleonard1** [comment]
I had the same problem using the current default python3 from Conda, python 3.9.1. I fixed install by using python 3.7. Error output below: 

| => python3 -m pip install KEGGDecoder
Collecting KEGGDecoder
  Downloading KEGGDecoder-1.2.2-py2.py3-none-any.whl (12.8 MB)
     |████████████████████████████████| 12.8 MB 3.4 MB/s 
Collecting biopython==1.74
  Downloading biopython-1.74.tar.gz (16.1 MB)
     |████████████████████████████████| 16.1 MB 9.2 MB/s 
Collecting matplotlib==3.0.3
  Downloading matplotlib-3.0.3.tar.gz (36.6 MB)
     |████████████████████████████████| 36.6 MB 17.0 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /Users/seanleonard/opt/miniconda3/envs/kegg_decoder/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/py/tglmn35d0nj70w0q28g7sq2w0000gn/T/pip-install-u2kmhrxl/matplotlib_415d448904d94507b22bbf47e2cb6cce/setup.py'"'"'; __file__='"'"'/private/var/folders/py/tglmn35d0nj70w0q28g7sq2w0000gn/T/pip-install-u2kmhrxl/matplotlib_415d448904d94507b22bbf47e2cb6cce/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/py/tglmn35d0nj70w0q28g7sq2w0000gn/T/pip-pip-egg-info-zkoun4so
         cwd: /private/var/folders/py/tglmn35d0nj70w0q28g7sq2w0000gn/T/pip-install-u2kmhrxl/matplotlib_415d448904d94507b22bbf47e2cb6cce/
    Complete output (43 lines):
    IMPORTANT WARNING:
        pkg-config is not installed.
        matplotlib may not be able to find some of its dependencies
    ============================================================================
    Edit setup.cfg to change the build options
    
    BUILDING MATPLOTLIB
                matplotlib: yes [3.0.3]
                    python: yes [3.9.1 | packaged by conda-forge | (default, Dec
                            9 2020, 01:10:56)  [Clang 11.0.0 ]]
                  platform: yes [darwin]
    
    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [not found. pip may install it below.]
          install_requires: yes [handled by setuptools]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
                       png: yes [version 1.6.26]
                     qhull: yes [pkg-config information for 'libqhull' could not
                            be found. Using local copy.]
    
    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]
    
    OPTIONAL BACKEND EXTENSIONS
                       agg: yes [installing]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                    macosx: yes [installing, darwin]
                 windowing: no  [Microsoft Windows only]
    
    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]
    
    ============================================================================
                            * The following required packages can not be built:
                            * freetype
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by bjtully** [comment]
See Issue #56 - this issue has to do with KEGG-Decoder only being tested for Python=3.6

Sorry for the confusion (and not responding sooner).
