### ISSUE TITLE
A not-yet-confirmed tip for grouping of genomes based on the name before the LAST underscore

### ISSUE THREAD

**Issue by ilnamkang** [bjtully/BioData#45]
Hi,

Sometimes, I prefer naming my MAGs with a format "sample_serial". If a sample name is SP, then the MAGs will be named SP_01, SP_02, and so on. In this case, a merged KEGG output file would look like below.

SP_01_00001	K00370
SP_01_00002	K00371
SP_01_00003	K00372
SP_02_00001	K01230
SP_02_00002	K01231
SP_02_00003	K01234

If I perform KEGG-Decoder with this file, the output will contain only one genome named "SP".

So, I tried modifying KEGG_decoder.py. When I modified lines 1410, 1411, 1413 (for the current version) as below, the result came out as I wanted.

info[0].split("\_")[0] --> info[0].rsplit("\_",1)[0]

Because I have little knowledge in Python and this tip is from just Google searches, I wish someone would check whether this modification has no unintended effects on the results.

Thanks.

**Comment by bjtully** [comment]
Hi!

This works for the example you have provided. And should not have an impact on the results.

If you had something like:
SP_01_a_00001 K00370
SP_01_a_00002 K00371
SP_01_b_00001 K01230
SP_01_b_00002 K01231
This line of code would merge the two genomes (SP_01_a & SP_01_b) into SP_01, as it only maintains the information before the second "_".
