### ISSUE TITLE
truncate heatmap from KEGGDecoder

### ISSUE THREAD

**Issue by liupfskygre** [bjtully/BioData#48]
Hi,
   I installed KEGGDecoder and it ran well on one of my files but truncate the heatmap of the other with no error reported. Could not figure out why since the small file is just a subset the other one. 

I have python 3.7 and a conda env, pip installed KEGGdecoder. 

Thanks. 

conda activate Decoder
KEGG-decoder --input 1.txt --output 1.list --vizoption interactive

#UBA9217, with new r95, 49 were assign as UBA9217

KEGG-decoder --input 2.txt --output 2.list --vizoption interactive 

#the truncated heatmap
![newplot (1)](https://user-images.githubusercontent.com/5625829/91052442-0abcad00-e654-11ea-982c-ffba9041a63a.png)

this is my file, with 1.txt fine and 2.txt truncate
[2.txt](https://github.com/bjtully/BioData/files/5118213/2.txt)

[1.txt](https://github.com/bjtully/BioData/files/5118212/1.txt)

**Comment by bjtully** [comment]
Thanks for finding this! It seems there is a bug in the visualization code that truncates the interactive output file when there is between 25-49 genomes and then another issue for 50-99 genomes. I will try and push out a corrected version soon.

**Comment by liupfskygre** [comment]
thanks, expecting the corrected version soon. now cut into <25.

**Comment by bjtully** [comment]
Not sure how 24 days have elpased on this - but I think I've got the Plotly settings right such that all ranges of genomes should display with interactive mode with pip v1.2.2

Let me know if you stumble across more problems.
