### ISSUE TITLE
Wood Ljungdahl Defintions

### ISSUE THREAD

**Issue by waoverholt** [bjtully/BioData#49]
Is there a typo for option 2 in the Wood Ljungdahl section of the KOALA_definitions.txt file?

Should it be:
acsB (K14138) AND CODH (cooS; K00198) OR aerobic CODH (coxSML; K03518 + K03519 + K03520)

Rather than:
acsB + cooS + coxSML

**Comment by bjtully** [comment]
You are correct @waoverholt it is a typo. I will change the text to read -- 

> Option 1 (when fused) - acetyl-CoA decarbonylase/synthase complex subunit alpha K00192 **AND carbon-monoxide dehydrogenase K00198 + K00196 OR carbon-monoxide dehydrogenase K03520 + K03518 + K03519**
> Option 2 - CO-methylating acetyl-CoA synthase K14138 **AND carbon-monoxide dehydrogenase K00198 + K00196 OR carbon-monoxide dehydrogenase K03520 + K03518 + K03519**

KEGG-Decoder actually functions by checking if either acetyl-CoA decarbonylase/synthase complex subunit alpha (K00192) OR CO-methylating acetyl-CoA synthase (K14138) is present to determine which CO-methylating step occurs 
and
then checks for aerobic (K03520) OR anaerobic (K00198) carbon-monoxide dehydrogrenase.
