### ISSUE TITLE
Regarding Kegg_decoder and expander

### ISSUE THREAD

**Issue by razz1618** [bjtully/BioData#50]
Hi,
I recently ran the module on my data. My query is how the range (0-1) for heatmap (txt and figure) is assigned.

For e.g., this function_out.list 
Function | glycolysis | gluconeogenesis | TCA Cycle | NAD(P)H-quinone oxidoreductase | NADH-quinone oxidoreductase

genecall | 1 | 1 | 1 | 0.98 | 0.98

On what basis these numbers are decided. If it is related to completion of a pathway, how to infer the results?

**Comment by bjtully** [comment]
Hi!

Yes. The values express the completion of the pathway and/or presence/absence of a process which is controlled by a single protein.

More details about which KEGG IDs are checked for a pathway or process can be found in this text file: https://github.com/bjtully/BioData/blob/master/KEGGDecoder/KOALA_definitions.txt

For e.g.
glycolysis is measured by the fraction of 8 steps (checking for 13 proteins, some of which can substitute for each other) present in a genome/sample
chitinase is either the presence or absence (0 or 1) of the KEGG ID for that function.

Hope this clarifies things.

**Comment by razz1618** [comment]
I see. so, if a process involves 10 different proteins and the annotation data shows presence of only 6 of them, does it mean the value will be 0.6.

I am primarily focused on genes involved in the Nitrogen cycle. From the KOALA_definations.txt file, I find you have mentioned-
 
Dissimilatory nitrate reduction requires narGH K00370 + K00371 AND/OR napAB K02567 + K02568

In fact, this is only half of the process wherein Nitrate (NO3) is converted to nitrite (NO2), the important part for DNRA is the conversion of NO2 to ammonia (NH4). Without tracking the ammonia conversion step, we do not know whether the NO2 will be retained as NH4 or removed as N2 gas (Denitrification)

Nitrate ---- (K00370, K00371, K02567, K02568)------> Nitrite ----(K00362, K00363, K03385, K15876).

**Comment by bjtully** [comment]
The entry for DNRA is a few lines below dissimilatory nitrate reduction
DNRA requires nirBD (K00362 + K00363) and/or nrfAH K03385 + K15876

**Comment by razz1618** [comment]
Ohh..sorry. i completely missed that line. my bad.

**Comment by bjtully** [comment]
No problem. I always appreciate someone double-checking the work. A bulk of relationships were done in 2017, so updates and changes are to be expected.

**Comment by razz1618** [comment]
Thanks, for the module. it really makes the complex pathways crisper and clear.
