### ISSUE TITLE
TSV output format

### ISSUE THREAD

**Issue by zooniikayler** [bjtully/BioData#55]
Hiya, 
I'm here from the BVCN youtube channel and hoping to use KEGG-decoder for a project. I was hoping to use the TSV output to create my own heatmaps but the format I'm getting doesn't seem to be columns of pathways and rows of samples. I attached one of my function_out.list files. 
[kegg-decoder-output_matanushka1.txt](https://github.com/bjtully/BioData/files/6376604/kegg-decoder-output_matanushka1.txt)

**Comment by bjtully** [comment]
My guess would be that all of your gene IDs start with `NODE_`, right? KEGG-Decoder is a simple script and use the formatting in the first column to determine which genome to assign functions to.
Ideally you'd want something like:
```
GENOME1_GENE1	KO
GENOME1_GENE2	KO
GENOME2_GENE1	KO
```
KEGG-Decoder will provide output for GENOME1 and GENOME2. Everything before the first "_" is the name of the genome.
If you have something like:
```
NODE_GENOME1_GENE1	KO
NODE_GENOME2_GENE1	KO
```
KEGG-Decoder will provide one output for NODE
