### ISSUE TITLE
methanogenesis via methylamines grouping

### ISSUE THREAD

**Issue by AstrobioMike** [bjtully/BioData#58]
Heya!

Thanks all for the work on keggdecoder, is it super-helpful in grouping/summarizing :)

Some data led me to looking more closely at "[methanogenesis via trimethylamine](https://github.com/bjtully/BioData/blob/cb1d45a957eda783412a48911c8592252915d9cd/KEGGDecoder/KOALA_definitions.txt#L280)", which is currently flagged as complete with solely [K14083](https://www.genome.jp/dbget-bin/www_bget?K14083) being detected, which is a trimethylamine methyltransferase. 

In my limited looking into this, i think we need methyl coenzyme M reductase also? Sticking to KEGG and looking on the [module page](https://www.genome.jp/module/M00563), it looks like K14083 (and maybe needing K14084 also(?)) is listed as taking trimethylamine to this [intermediate C03920 compound](https://www.genome.jp/dbget-bin/www_bget?C03920), which then is expected to require K00399, K00401, and K00402 to perform [reaction R04541](https://www.genome.jp/entry/R04541) to actually generate methane. 

It also seems something similar might be going on for the other things listed as "[methanogenesis via ...](https://github.com/bjtully/BioData/blob/cb1d45a957eda783412a48911c8592252915d9cd/KEGGDecoder/KOALA_definitions.txt#L267)", where these are being marked as complete if genes are present for just this first step, and not requiring the follow-up that produces methane.

If i'm not confusing myself here and the above looks right to others, do you think it makes more sense to have the modules like  "methanogenesis via trimethylamine" require K00399, K00401, and K00402 also? Or, if they are deliberately kept separate, with the intent that the enzyme those 3 make up is represented in the ["coenzyme M reduction to methane" grouping](https://github.com/bjtully/BioData/blob/cb1d45a957eda783412a48911c8592252915d9cd/KEGGDecoder/KOALA_definitions.txt#L294), then maybe the others should just be labeled as, e.g., "trimethylamine methyltransferase" rather than "methanogenesis via trimethylamine"? 

I'm happy to submit a pull request with the appropriate modifications if that'd be helpful, but I also wanted to have a second set of eyes on what i'm thinking to make sure i'm not just confused.

Thanks!

**Comment by bjtully** [comment]
It is currently intentional. To be functional methanogenesis requires:
Coenzyme M reduction to methane
	K00399 + K00401 + K00402 mcrABCD; methyl-coenzyme M reductase
&
Coenzyme B/Coenzyme M regeneration
	K03388 + K03389 + K03390 + K08264 + K08265 hdrABCDE; CoB-CoM heterodisulfide reductase
&
a source for the methyl group being converted to methane (or reduced from CO2). All of the "methanogenesis via..." entries are to determine the source of the methyl group.

It is currently worded this way because I wrote it and I understand it, but I get that it might be confusing.

**Comment by AstrobioMike** [comment]
ah i dig. Yea i do think the labels are a little confusing, as saying "methanogenesis via ..." reads to me like it is evaluating the completeness of the methanogenesis pathway including that source, rather than just the source. But i get the value of having them split. If you think it's too clunky making them something like "source of methanogenesis via trimethylamine" or "methanogenesis via trimethylamine (source)", then i don't have any better ideas either. Adding your response at the top of the [the methanogenesis section](https://github.com/bjtully/BioData/blob/cb1d45a957eda783412a48911c8592252915d9cd/KEGGDecoder/KOALA_definitions.txt#L267) would be helpful too though :) 

Thanks for the quick clarification!
